src/web/mysite/urls.py
from django.urls import path, include

from mysite.views import indexView, RegisterView, TaskCreateView, TaskCompleteView, TaskBackView, TaskDeleteView

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', indexView, name='index'),
    path('register/', RegisterView.as_view(), name='register'),
    path('create_task/', TaskCreateView.as_view(), name='create_task'),
    path('complete_task/<int:task_id>', TaskCompleteView.as_view(), name='complete_task'),
    path('back_task/<int:task_id>', TaskBackView.as_view(), name='back_task'),
    path('delete_task/<int:task_id>', TaskDeleteView.as_view(), name='delete_task'),
]

src/web/web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    path('admin/', admin.site.urls, name='admin_panel'),
    path('', include('mysite.urls')),
    path('api/v1/', include('admin_web.urls')),
]

src/web/mysite/forms/register.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from admin_web.models import Telegram


class RegisterForm(UserCreationForm):
    telegram = forms.IntegerField()

    def save_and_telegram(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
            if hasattr(self, "save_m2m"):
                self.save_m2m()
        Telegram(user=user, telegram_id=self.cleaned_data["telegram"]).save()
        return user

src/web/mysite/forms/tasks.py
from django import forms


class TaskCreateForm(forms.Form):
    title = forms.CharField(max_length=64)
    description = forms.CharField(max_length=512)

src/web/mysite/views/index.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from admin_web.models import Task


@login_required(login_url='/login/')
def indexView(request):
    user = request.user
    tasks = Task.objects.filter(user=user).all()
    context = {
        "tasks": tasks
    }
    return render(request, 'mysite/../../templates/mysite/index.html', context)

src/web/mysite/views/register.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.views import View

from mysite.forms.register import RegisterForm


class RegisterView(View):
    template_name = 'registration/register.html'

    def get(self, request):
        context = {
            'form': RegisterForm()
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = RegisterForm(request.POST)

        if form.is_valid():
            user = form.save_and_telegram()
            login(self.request, user)
            messages.success(request, 'Регистрация прошла успешна')
            return redirect('index')
        context = {
            'form': form
        }
        return render(request, self.template_name, context)

src/web/mysite/views/tasks.py
from django.contrib import messages
from django.shortcuts import redirect
from django.views import View

from admin_web.models import Task
from mysite.forms import TaskCreateForm


class TaskCreateView(View):
    template_name = 'mysite/index.html'

    def post(self, request):
        form = TaskCreateForm(request.POST)

        if form.is_valid():
            Task(
                user=request.user, title=form.cleaned_data["title"], description=form.cleaned_data["description"]
            ).save()
            messages.success(request, 'Новая запись добавлена успешно!')
            return redirect('index')
        context = {'form': form}
        return redirect(request, self.template_name, context)


class TaskCompleteView(View):
    def get(self, request, task_id):
        task = Task.objects.get(id=task_id)
        task.close = True
        task.save()
        return redirect('index')


class TaskBackView(View):
    def get(self, request, task_id):
        task = Task.objects.get(id=task_id)
        task.close = False
        task.save()
        return redirect('index')


class TaskDeleteView(View):
    def get(self, request, task_id):
        Task.objects.get(id=task_id).delete()
        return redirect('index')

src/web/templates/mysite/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>{% block  title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
<main class="container-xxl">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
            <div class="col m-1 col-sm-3">
                <div class="row">
                    <a class="navbar-brand" href="{% url 'index' %}">ToDoList</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarCollapse"
                            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
            </div>

            {% if user.is_authenticated %}
                <div class="col m-1 col-sm-3">
                    <div class="row">
                        <button class="btn col m-1" disabled>
                            <a class="nav-link text-light">{{ user }}</a>
                        </button>
                        <button class="btn btn-outline-success col m-1">
                            <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                        </button>
                        {% if user.is_superuser %}
                            <button class="btn btn-outline-success col m-1">
                                <a class="nav-link" href="/admin">Админ</a>
                            </button>
                        {% endif %}
                    </div>
                </div>
            {% else %}
                <div class="col m-1 col-sm-2">
                    <div class="row">
                        <button class="btn btn-outline-success col m-1">
                            <a class="nav-link" href="{% url 'login' %}">Вход</a>
                        </button>
                        <button class="btn btn-outline-success col m-1">
                            <a class="nav-link" href="{% url 'register' %}">Регистрация</a>
                        </button>

                    </div>
                </div>
            {% endif %}
        </div>
    </nav>
    <p class="text-center fs-2">
        {% block inside_title %}{% endblock %}
    </p>
    <div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}"> {{ message|safe }} </div>
            {% endfor %}
        {% endif %}
    </div>

    {% block content %}{% endblock %}
</main>
</body>
</html>

src/web/templates/mysite/index.html
{% extends 'mysite/base.html' %}

{% block title %}Главная страница{% endblock %}

{% block inside_title %}Задачи{% endblock %}

{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container ">
            <div class="row">
                <form action="{% url 'create_task' %}" method="post">
                    <div class="text-center">
                        <div class="mb-3">
                            <label class="form-label" for="id_title">Заголовок</label>
                            <input class="form-control" type="text" name="title" maxlength="64" required=""
                                   id="id_title">
                        </div>
                        <div class="mb-3">
                            <label class="form-label" for="id_description">Описание</label>
                            <textarea class="form-control" name="description" required=""
                                      id="id_description"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Добавить запись</button>
                        {% csrf_token %}
                    </div>

                </form>
            </div>
            <br>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for task in tasks %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <h5 class="card-title">{{ task.title }} {% if task.close %}✓{% endif %}</h5>
                                <p class="card-text">
                                    {{ task.description }}
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        {% if task.close %}
                                            <div class="btn-group">
                                                <a href="{% url 'back_task' task_id=task.id %}">
                                                    <button type="button" class="btn btn-sm btn-outline-secondary">
                                                        Вернуть
                                                    </button>
                                                </a>
                                            </div>
                                        {% else %}
                                            <div class="btn-group">
                                                <a href="{% url 'complete_task' task_id=task.id %}">
                                                    <button type="button" class="btn btn-sm btn-outline-secondary">
                                                        Завершить
                                                    </button>
                                                </a>
                                            </div>
                                        {% endif %}
                                        <div class="btn-group">
                                            <a href="{% url 'delete_task' task_id=task.id %}">
                                                <button type="button" class="btn btn-sm btn-outline-secondary">
                                                    Удалить
                                                </button>
                                            </a>
                                        </div>
                                    </div>
                                    <small class="text-body-secondary">{{ task.created_at }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}